### PR TITLE
Enable dark mode in the template

### PR DESCRIPTION
**Pull request by rahulrai-in**
Hi @kongdivin, I have made the changes to enable dark mode in the template. I am not an expert in front-end, so I request you to provide critically review the changes and provide feedback. Here is a snapshot of the dummy application in action with the changes in place.

ezgif com-gif-maker

### CODE REVIEW

**Comment by kongdivin** [comment]
Hi @rahulrai-in,

First of all, thank you for the PR!

I haven't reviewed at the code yet, but it looks promising. However, I have a few comments on the UX/UI.

1. The Toggle doesn't have anything to indicate its functionality, so the readers might not know what it does exactly.
1. The placement of the Toggle is kind of non-conventional. Would you mind telling me why you chose this placement? For what it's worth, here are some suggestions:
    * At the top most right corner (maybe in the menu bar) E.g. https://overreacted.io/
    * At the bottom right corner (my preference). E.g. https://ant.design/components/overview/
    * In the footer. E.g. https://hexdocs.pm/iex/api-reference.html#modules
1. The theme is responsive, so you might want to test it on smaller screens also.
1. The *tags*, *links*, and *code* text color is really hard to see. You may want to check the color contrast ratio for accessibility purposes -- https://color.a11y.com/.

P.S. Can you also make it configurable so that users don't have to pay the cost if they don't need this feature?

**Comment by rahulrai-in** [comment]
Hi @kongdivin,

Thanks for the feedback. I will have another go at the PR somewhere around the end of this month. I would like to understand your thinking behind the current UX. I can see that you have only used controls and CSS of the Vanilla framework. I was planning to redesign the toggle but used the toggle of Vanilla framework anyway to maintain consistency. Are you open to use a different control for the toggle?

By placing the control on the bottom right, some of the screen real estate on mobile devices is wasted, and placing it in the footer would mean that people might not notice that it even exists. Are you open to placing it in front of the search box?

If you look at the code, you can see that I was trying to override the styles applied by Vanilla f\w. However, Vanilla framework has a theming option available as well. Are you planning to switch to this option in the future? https://vanillaframework.io/docs/settings/color-settings

**Comment by kongdivin** [comment]
@rahulrai-in — I don't mind having another toggle control specifically designed for night/dark mode as long as it can be disabled/excluded through configurations. Putting it next to the search box sounds good to me.

Regarding theming in Vanilla, currently only a subset of elements/components are available in dark theme. Although we don't really use many elements in this theme, I still prefer waiting for a bit before working on that. Plus, I don't really have time to work on this at the moment. That said, if you want to incorporate it in this theme, I'm happy to discuss how we should go about it.

**Comment by rahulrai-in** [comment]
Here is what I have so far. Let me know if this looks good to you.

Desktop view
image

Small screen view minimized
image

Small screen maximized
image

I will raise a PR if the control placement looks fine to you.

**Comment by rahulrai-in** [comment]
Hi, @kongdivin The template is now ready to be merged. Here is the final output. I have taken care of the accessibility and used a very informative icon similar to that used on the v8.dev website. The template is also responsive. Can you provide your feedback to it? I have also ensured that the website defaults to light theme if localstorage is not available in cases such as incognito browser window.
2020-07-25_01h34_46

**Comment by rahulrai-in** [comment]
Hi @kongdivin. I found a couple of issues and I have addressed them. The changes are ready now.

**Comment by kongdivin** [comment]
Wow, it looks amazing. However, I wouldn't be able to review it until mid August due to my current workload. Thank you for your patience and the hard work.

**Comment by rahulrai-in** [comment]
No issues with keeping the PR open for some time. I am going to take my current fork of the theme and use it till you have some time to revisit it. Thanks for building the original theme and keeping it up to date.

**Comment by rahulrai-in** [comment]
@kongdivin any chance to get this merged soon?

**Comment by kongdivin** [comment]
@rahulrai-in -- sorry, but I will only be able to review this in 2 weeks.

**Comment by rahulrai-in** [comment]
Thanks for the comments @kongdivin. I will close this PR and keep the changes in my fork.

**Pull request closed without merging**
